### ISSUE TITLE
Can you publish djwt to npmjs ?

### ISSUE THREAD

**Issue by UrielCh** [Zaubrik/djwt#82]
Hi, I have to convert one of my deno project to nodeJS, and your project is not available for it.

I use jsonwebtoken instead, but its interface is different, so I have to change my code.

I used Deno dnt in multiple projects in the past if that can help.

**Comment by timonson** [comment]
Hi,

I personally won't do that. But I am considering adding a bundled JS file here. Would it help you?

**Comment by UrielCh** [comment]
I can add some dnt build script, but a custom bundler script takes longer.

**Comment by timonson** [comment]
Interesting, could I implement it as an Github action somehow so that I won't have to do anything?

**Comment by UrielCh** [comment]
this is an example of my recent dnt integration:

a build script: [_build_npm.ts](https://github.com/deno-library/logger/blob/master/_build_npm.ts)
a publish action: [deno-publish.yml](https://github.com/deno-library/logger/blob/master/.github/workflows/deno-publish.yml)

or an other one:
- [_build_npm.ts](https://github.com/UrielCh/midjourney-client/blob/main/_build_npm.ts)
- [action](https://github.com/UrielCh/midjourney-client/blob/main/.github/workflows/deno-publish.yml)

**Comment by hansSchall** [comment]
Once djwt has been published to JSR (#85) it can be installed using the JSR NPM compat layer

**Comment by timonson** [comment]
Does this [PR](https://github.com/Zaubrik/djwt/pull/85) work for our use case here?

**Comment by timonson** [comment]
Something went wrong. Can anybody help?

@emrahcom something went wrong with CI. Would you mind taking a look into it?

https://github.com/Zaubrik/djwt/actions/runs/10150942921/job/28069171066

> error: Import 'https://registry-staging.deno.com/@std/encoding/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@std/encoding/meta.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at file:///Users/runner/work/djwt/djwt/deps.ts:4:8

**Comment by timonson** [comment]
I did it with `deno publish` manually now.

https://jsr.io/@zaubrik/djwt@3.0.2

**Comment by emrahcom** [comment]
Hi @timonson, looks like there is a problem with DNS record of `registry-staging.deno.com`. So, `test.yml` failed while running `deno test -A`.

But if I run the same command (`deno test -A`) in my local, it works. I'm not sure if this is a temporary problem or not.

**Comment by emrahcom** [comment]
Looks like `test.yml` fails with `old` deno.

**Comment by timonson** [comment]
> Looks like `test.yml` fails with `old` deno.

You are right. It works now. Can I close this issue now or is something still missing for npm?

**Comment by timonson** [comment]
Thanks @emrahcom , I just changed *main* to *master*.
