### ISSUE TITLE
can create but not validate a JWT with a non-object payload

### ISSUE THREAD

**Issue by hankatola** [Zaubrik/djwt#83]
djwt@v2.9.1 djwt/mod.ts,&nbsp; the `validate` function throws an error  when the payload argument in the JWT that has been created with the `create` function is a string instead of a generic object, i.e.

```js
const jwt = await create(header, "foo", key) // works
const verifiedJWT = await verify(jwt, key) // throws error "The jwt claims set is not a JSON object" from line 186
```

In order to prevent both further confusion and invalid jwts from being created, if the `payload` argument must be an object, the error should be thrown in the `create` function, i.e.

```js
const jwt2 = await create(header, {msg: "foo"}, key) // should (and does) work
const jwt3 = await create(header, "foo", key) // should throw error `The jwt payload is not an object`
```
If `payload` argument is not required to be a generic object (i.e. strings/numbers/etc... should be acceptable), then the `validate` function needs to be adjusted.

**Comment by timonson** [comment]
Hi @hankatola ,

are you using JavaScript or TypeScript?

In TS I am getting this error:

> error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'Payload'.
console.log(await create(header, "foo", key));

But I agree that it should throw in JS, as well.

**Comment by hankatola** [comment]
JavaScript

**Comment by timonson** [comment]
Thank you @hankatola ,

I fixed your issue with https://github.com/Zaubrik/djwt/pull/84 .

Please let me know if you have further issues, especially with JavaScript.
